### ISSUE TITLE
Hello,你的Lisence是不是写错了?

### ISSUE THREAD

**Issue by devSC** [coderyi/Monkey#1]
现在是:"此开源项目可以用来做任何事情除了原封不动的分发到App Store。"
你是不是想说: "此开源项目可以用来做任何事情除了不能原封不动的分发到App Store。" ?

**Comment by ZsIsMe** [comment]
devSC，你弄混了，
“除了”，就是不包括，不能，
“除了不能”，负负得正，就是“可以”。

**Comment by coderyi** [comment]
哈哈哈，😄

**Comment by a90120411** [comment]
讨论语文呢。

**Comment by yizhiheng** [comment]
哈哈第一个对吧
