### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by AmirDaliri** [coderyi/Monkey#21]
Are you write monkey for swift???
i need it :/

**Comment by coderyi** [comment]
What do you need it to do? I haven't written swift version yet.

**Comment by AmirDaliri** [comment]
Hi bro ,first thank you for your attention.
our company asked  me it's as a test, i want to show github user with alamofire in swift 2.2 .
can you help me ?

**Comment by coderyi** [comment]
you can use this API;

```
https://api.github.com/search/users?q=language:swift&sort=followers&order=desc
https://api.github.com/search/users?sort=followers&page=1&q=location:iran+language:javascript
```
