### ISSUE TITLE
想问一下Trending的API是通过search的API获得的吗？那怎样以某段时间的star数来排序呢？

### ISSUE THREAD

**Issue by 22Nathan** [coderyi/Monkey#26]
在官方文档里没找到..所以来请教下，谢谢

**Comment by coderyi** [comment]
不是通过search，是通过第三方抓取的，
可以看一下这里，https://github.com/coderyi/Monkey/blob/master/Monkey/MonkeyKit/NetworkEngine/YiNetworkEngine.h

**Comment by 22Nathan** [comment]
好的了解了，谢谢~
