### ISSUE TITLE
是否有计划把一些UI交互改进呢？

### ISSUE THREAD

**Issue by xhzengAIB** [coderyi/Monkey#3]
我乐意加入

比如：
Page Viewer   --->  网易
Repositoires   ---->  Sina Pop List Menu

NavigationBar or TabBar的美化等等！

Jack

**Comment by coderyi** [comment]
昨天有一位朋友对UI也提了一些问题，他说帮我设计一下，等几天出来看一下是什么样的，到时候给你也看一下！非常高兴你愿意帮助，我尽快整理出一下新版本更新需要做的计划，“Repositoires ----> Sina Pop List Menu”是什么，你现在在写了吗？Jack

**Comment by xhzengAIB** [comment]
pop list好像不适合用在这里

**Comment by coderyi** [comment]
现在tab只有三个 ，我准备加一个tab，把github trending  和登录，个人动态做进去

**Comment by xhzengAIB** [comment]
好的，等设计稿出来

**Comment by coderyi** [comment]
嗯  到时候我联系你

**Comment by booxood** [comment]
我在用 React Native 做一个仿 Monkey 的
新的设计，可以先参考下吗？
:smile:

**Comment by coderyi** [comment]
可以啊！你在做一个什么App呢？

**Comment by booxood** [comment]
@coderyi 就是仿你这个的啦。。。
