### ISSUE TITLE
github_top_users_objective-c_world.md 文件的链接

### ISSUE THREAD

**Issue by xiilei** [coderyi/Monkey#7]
https://github.com/coderyi/Monkey/blob/master/github_top_users_repositories/github_top_users_objective-c_world.md
这个文件的第一个链接写了编辑文件的链接
https://github.com/coderyi/Monkey/edit/master/github_top_users_repositories/github_top_users_objective-c_world.md
其他人可能访问有点权限限制

**Comment by coderyi** [comment]
谢谢您的提醒，已经修改了
